---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, videos, policies, json, api, ontap, release notes, bugs, limitations, known issues, permissions, apis 
summary: Cloud Manager と Cloud Volumes ONTAP の詳細については、ビデオ、フォーラム、サポートなどのさまざまなリソースを参照してください。 
---
= ヘルプを参照したり、詳細情報を参照したりするには
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager と Cloud Volumes ONTAP の詳細については、ビデオ、フォーラム、サポートなどのさまざまなリソースを参照してください。

* https://["Cloud Manager と Cloud Volumes ONTAP のビデオ"^]
+
Cloud Volumes ONTAP を AWS と Azure に導入して管理する方法と、ハイブリッドクラウド全体でデータをレプリケートする方法を紹介するビデオをご覧ください。

* http://["Cloud Manager のポリシー"^]
+
Cloud Manager が AWS および Azure でアクションを実行するために必要な権限を含む JSON ファイルをダウンロードします。

* link:api.html["Cloud Manager API 開発者ガイド"^]
+
API の概要、使用方法の例、 API リファレンスを紹介します。

* Cloud Volumes ONTAP のトレーニング
+
** https://["Cloud Volumes ONTAP の基礎"^]
** https://["Azure 向け Cloud Volumes ONTAP の導入と管理"^]


* テクニカルレポート
+
** https://["NetApp テクニカルレポート 4383 ：アプリケーションワークロードを使用した Amazon Web Services における Cloud Volumes ONTAP のパフォーマンス特性"^]
** https://["NetApp テクニカルレポート 4671 ：アプリケーションワークロードを使用した Azure における Cloud Volumes ONTAP のパフォーマンス特性評価"^]


* https://["『 Cloud Volumes ONTAP 9SVM Disaster Recovery Preparation Express Guide 』を参照してください"^]
+
ディザスタリカバリに備えて、デスティネーション SVM を迅速に設定する方法について説明します。

* https://["『 Cloud Volumes ONTAP 9SVM Disaster Recovery Express Guide 』を参照してください"^]
+
災害発生後にデスティネーション SVM を迅速にアクティブ化し、ソース SVM を再アクティブ化する方法について説明します。

* http://["ONTAP 9 ドキュメンテーション・センター"^]
+
Cloud Volumes ONTAP の使用に役立つ ONTAP の製品マニュアルにアクセスしてください。

* https://["NetApp Cloud Volumes ONTAP のサポート"^]
+
サポートリソースにアクセスして、 Cloud Volumes ONTAP に関するヘルプやトラブルシューティングを参照してください。

* https://["ネットアップコミュニティ：クラウドデータサービス"^]
+
同僚とつながり、質問をしたり、アイデアを交換したり、リソースを見つけたり、ベストプラクティスを共有したりします。

* http://["NetApp Cloud Central"^]
+
クラウド向けのその他のネットアップ製品とソリューションに関する情報をご覧ください。

* http://["ネットアップの製品マニュアル"^]
+
手順、リソース、回答については、ネットアップの製品マニュアルを参照してください。


