---
sidebar: sidebar 
permalink: reference_networking_azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: Cloud Volumes ONTAP システムが正常に動作するように、 Azure ネットワークを設定する必要があります。 
---
= Azure の Cloud Volumes ONTAP のネットワーク要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP システムが正常に動作するように、 Azure ネットワークを設定する必要があります。

****
Cloud Manager がアクセスする必要があるエンドポイントのリストをお探しですか。これで、 1 つの場所で管理されるようになりました。 link:reference_networking_cloud_manager.html["詳細については、ここをクリックしてください。"]。

****
Cloud Volumes ONTAP 用のアウトバウンドインターネットアクセス:: Cloud Volumes ONTAP では、ネットアップ AutoSupport にメッセージを送信するためにアウトバウンドインターネットアクセスが必要です。ネットアップ AutoSupport は、ストレージの健全性をプロアクティブに監視します。
+
--
Cloud Volumes ONTAP から AutoSupport メッセージを送信できるように、ルーティングポリシーとファイアウォールポリシーで次のエンドポイントへの AWS HTTP/HTTPS トラフィックを許可する必要があります。

* \ https://support.netapp.com/aods/asupmessage
* \ https://support.netapp.com/asupprod/post/1.0/postAsup


--
セキュリティグループ:: Cloud Manager ではセキュリティグループを作成する必要がないため、セキュリティグループを作成する必要はありません。自分で使用する必要がある場合は、を参照してください link:reference_security_groups_azure.html["セキュリティグループのルール"]。
クラウドボリューム ONTAP から Azure BLOB ストレージへの接続により、データ階層化を実現します:: コールドデータを Azure BLOB ストレージに階層化する場合は、 Cloud Manager に必要な権限が付与されていれば VNet サービスエンドポイントを設定する必要はありません。
+
--
[source, json]
----
"Microsoft.Network/virtualNetworks/subnets/write",
"Microsoft.Network/routeTables/join/action",
----
これらの権限は最新のに含まれています https://["Cloud Manager ポリシー"]。

データ階層化の設定の詳細については、を参照してください link:task_tiering.html["コールドデータを低コストのオブジェクトストレージに階層化する"]。

--
他のネットワーク内の ONTAP システムへの接続:: Azure の Cloud Volumes ONTAP システムと他のネットワークの ONTAP システムの間でデータをレプリケートするには、 Azure VNet と他のネットワーク（ AWS VPC や企業ネットワークなど）の間に VPN 接続が必要です。
+
--
手順については、を参照してください https://["Microsoft Azure のドキュメント：「 Create a Site-to-Site connection in the Azure portal"^]。

--

