---
sidebar: sidebar 
permalink: reference_infrastructure_as_code.html 
keywords: ansible, playbook, automation 
summary: DevOps チームは、さまざまなツールを使用して新しい環境のセットアップを自動化し、インフラをコードとして扱うことができます。Ansible と Terraform の 2 つのツールがあります。ネットアップでは、 Ansible と Terraform のサンプルを開発しました。このサンプルを使用することで、 DevOps チームは Cloud Manager を使用して Cloud Volumes ONTAP を自動化し、コードとしてインフラと統合できます。 
---
= コードとしてのインフラの自動化サンプル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このページのリソースを使用して、の統合を支援します Cloud Manager と Cloud Volumes ONTAP の組み合わせをで使用できます https://["コードとしてのインフラ"^]。

DevOps チームは、さまざまなツールを使用して新しい環境のセットアップを自動化し、インフラをコードとして扱うことができます。Ansible と Terraform の 2 つのツールがあります。ネットアップでは、 Ansible と Terraform のサンプルを開発しました。このサンプルを使用することで、 DevOps チームは Cloud Manager を使用して Cloud Volumes ONTAP を自動化し、コードとしてインフラと統合できます。

https://["自動化のサンプルを表示します"^]。

たとえば、サンプルの Ansible プレイブックを使用して、 Cloud Manager と Cloud Volumes ONTAP を導入し、アグリゲートを作成し、ボリュームを作成できます。環境のサンプルを変更するか、サンプルに基づいて新しいプレイブックを作成します。

* 関連リンク *

* https://["NetApp Cloud ブログ： Using Cloud Manager REST API with Federated Access"^]
* https://["ネットアップのクラウドブログ：「 Cloud Automation with Cloud Volumes ONTAP and REST"^]
* https://["ネットアップのクラウドブログ： Automated Data Cloning for Cloud Based Testing of Software Applications"^]
* https://["ネットアップのブログ：「 Infrastructure-as-Code （ IAC ） Accelerated with Ansible + NetApp"^]
* https://["NetApp thePub ： Ansible による構成管理と自動化"^]
* https://["NetApp thePub ： Ansible ONTAP の役割"^]

