---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: Cloud Manager と Cloud Volumes ONTAP のデフォルト設定方法の詳細は、システムの管理に役立ちます。 
---
= デフォルト設定
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager と Cloud Volumes ONTAP のデフォルト設定方法の詳細は、システムの管理に役立ちます。



== Linux での Cloud Manager のデフォルト設定

Cloud Manager または Linux ホストのトラブルシューティングを行う必要がある場合は、 Cloud Manager の設定方法を理解することができます。

* NetApp Cloud Central から（または AWS Marketplace または Azure Marketplace から直接） Cloud Manager を導入した場合は、次の点に注意してください。
+
** AWS では、 EC2 Linux インスタンスのユーザ名は EC2-user です。
** AWS と Azure のどちらの場合も、 Cloud Manager イメージのオペレーティングシステムは Red Hat Enterprise Linux 7.4 （ HVM ）です。
+
オペレーティングシステムには GUI は含まれていません。システムにアクセスするには、端末を使用する必要があります。



* Cloud Manager のインストールフォルダは、次の場所にあります。
+
/opt/application/netapp/cloudmanager です

* ログファイルは次のフォルダに格納されます。
+
/opt/application/netapp/cloudmanager/log を選択します

* Cloud Manager サービスの名前は occm です。
* OCCM サービスは MySQL サービスに依存します。
+
MySQL サービスがダウンしている場合は、 OCCM サービスもダウンしています。

* 次のパッケージがまだインストールされていない場合は、 Cloud Manager によって Linux ホストにインストールされます。
+
** 7 郵便番号
** AWSCLI
** Java
** Kubectl のように入力する
** MySQL
** Tridentctl
** 取得






== Cloud Volumes ONTAP のデフォルト設定

Cloud Volumes ONTAP がデフォルトでどのように設定されているかを理解すると、システムのセットアップと管理に役立ちます。特に、 ONTAP に精通している場合は、 Cloud Volumes ONTAP のデフォルト設定は ONTAP とは異なるためです。

* Cloud Volumes ONTAP は、シングルノードシステムとして、また AWS と Azure の両方で HA ペアとして使用できます。
* Cloud Manager は、 Cloud Volumes ONTAP の導入時に 1 つのデータサービス SVM を作成します。System Manager または CLI から別のデータサービス SVM を作成できますが、複数のデータサービス SVM を使用することはできません。
* デフォルトでは、いくつかのネットワークインターフェイスが作成されます。
+
** クラスタ管理 LIF
** クラスタ間 LIF
** ノード管理 LIF
** iSCSI データ LIF
** CIFS および NFS データ LIF
+

NOTE: EC2 の要件により、 Cloud Volumes ONTAP の LIF フェイルオーバーはデフォルトで無効になっています。LIF を別のポートに移行すると、インスタンス上の IP アドレスとネットワークインターフェイス間の外部マッピングが解除され、 LIF にアクセスできなくなります。



* Cloud Volumes ONTAP は、 HTTPS を使用して設定バックアップを Cloud Manager に送信します。
* Cloud Manager にログインすると、からバックアップにアクセスできます https://ipaddress/occm/offboxconfig/[]
* Cloud Manager は、他の管理ツール（ System Manager や CLI など）とは異なるボリューム属性をいくつか設定します。
+
次の表に、 Cloud Manager がデフォルトとは異なる設定にしたボリューム属性を示します。

+
[cols="15,85"]
|===
| 属性 | Cloud Manager によって設定される値 


| オートサイズモード | 成長 


| 最大オートサイズ  a| 
1,000 パーセント


NOTE: Cloud Manager 管理者は、この値を ［ 設定 ］ ページから変更できます。



| セキュリティ形式 | CIFS ボリューム UNIX の場合は NTFS 、 NFS ボリュームの場合は NTFS 


| スペースギャランティスタイル | なし 


| UNIX 権限（ NFS のみ） | 777 
|===
+
これらの属性の詳細については、 _volume create のマニュアルページを参照してください。





== Cloud Volumes ONTAP のブートデータとルートデータ

Cloud Manager は、ユーザデータ用のストレージに加えて、各 Cloud Volumes ONTAP システムのブートデータとルートデータ用のクラウドストレージも購入します。



=== AWS

* Cloud Volumes ONTAP ブートデータ用にプロビジョニングされた IOPS SSD ディスク × 1 。約 45 GB 、 1,250 PiOps
* Cloud Volumes ONTAP ルートデータ用の汎用 SSD ディスクの 1 つ。約 140 GB です
* ブートディスクとルートディスクごとに 1 つの EBS スナップショット


HA ペアでは、両方の Cloud Volumes ONTAP ノードがルートディスクをパートナーノードにレプリケートします。



=== Azure

* Cloud Volumes ONTAP ブートデータ用の Premium Storage SSD ディスク × 1 （約 73 GB ）
* Cloud Volumes ONTAP ルートデータ用の Premium Storage SSD ディスク × 1 （約 140 GB ）
* 各ブートディスクとルートディスクに 1 つの Azure Snapshot




=== ディスクが存在する場所

Cloud Manager は、 AWS と Azure のストレージを次のようにレイアウトします。

* ブートデータは、 EC2 インスタンスまたは Azure 仮想マシンに接続されたディスクに格納されます。
+
このディスクにはブートイメージが含まれており、 Cloud Volumes ONTAP では使用できません。

* システム構成とログを含むルートデータは、 aggr0 にあります。
* Storage Virtual Machine （ SVM ）ルートボリュームは aggr1 にあります。
* データボリュームも aggr1 にあります。

