---
sidebar: sidebar 
permalink: task_launching_aws_mktp.html 
keywords: install, installation, installing, marketplace, aws, launch, launching, ec2 console 
summary: NetApp Cloud Central を使用して AWS で Cloud Manager を起動することをお勧めしますが、必要に応じて AWS Marketplace から起動することもできます。 
---
= AWS Marketplace からの Cloud Manager の起動
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
を使用して、 AWS で Cloud Manager を起動することを推奨します https://["NetApp Cloud Central"^]必要に応じて、 AWS Marketplace から起動できます。


TIP: AWS Marketplace から Cloud Manager を起動しても、 Cloud Manager は NetApp Cloud Central と統合されたままです。 link:concept_cloud_central.html["統合の詳細については、こちらをご覧ください。"]。

.このタスクについて
以下の手順では、 EC2 コンソールからインスタンスを起動する方法について説明します。このコンソールでは、 IAM ロールを Cloud Manager インスタンスに関連付けることができます。これは、 1-Click オプションを使用しては実行できません。

.手順
. EC2 インスタンス用の IAM ポリシーとロールを作成します。
+
.. 次のサイトから Cloud Manager IAM ポリシーをダウンロードします。
+
https://["NetApp OnCommand Cloud Manager ： AWS と Azure のポリシー"^]

.. IAM コンソールから、 Cloud Manager IAM ポリシーからテキストをコピーアンドペーストして、独自のポリシーを作成します。
.. ロールタイプが Amazon EC2 の IAM ロールを作成し、前の手順で作成したポリシーをロールに付加します。


. にアクセスします https://["AWS Marketplace の Cloud Manager のページ"^]。
. [* Continue （続行） ] をクリックします
. Custom Launch タブで、お住まいの地域の * Launch with EC2 Console * をクリックして、次の項目を選択します。
+
.. リージョンの可用性に応じて、 t3.medium （推奨）、 t2.medium 、または m4.large インスタンスタイプを選択します。
.. 要件を満たす VPC 、サブネット、 IAM ロール、およびその他の設定オプションを選択します。
.. デフォルトのストレージオプションをそのまま使用します。
.. 必要に応じて、インスタンスのタグを入力します。
.. Cloud Manager インスタンスに必要な接続方法（ SSH 、 HTTP 、 HTTPS ）を指定します。
.. [* 起動 * ] をクリックします。




.結果
AWS は、指定した設定でソフトウェアを起動します。Cloud Manager インスタンスとソフトウェアは、約 5 分で実行されます。

.完了後
Web ブラウザにパブリック IP アドレスまたはプライベート IP アドレスを入力して Cloud Manager にログインし、セットアップウィザードを完了します。
