---
sidebar: sidebar 
permalink: task_installing_linux.html 
keywords: install, installation, installing, linux, installer, software, on prem, on-prem, silent 
summary: Cloud Manager を導入する最も一般的な方法は、 Cloud Central またはクラウドプロバイダのマーケットプレイスから入手する方法です。ただし、自社ネットワークまたはクラウドにある既存の Linux ホストに Cloud Manager ソフトウェアをダウンロードしてインストールすることもできます。 
---
= 既存の Linux ホストに Cloud Manager をインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager を導入する最も一般的な方法は、 Cloud Central またはクラウドプロバイダのマーケットプレイスから入手する方法です。ただし、自社ネットワークまたはクラウドにある既存の Linux ホストに Cloud Manager ソフトウェアをダウンロードしてインストールすることもできます。

.作業を開始する前に
* Red Hat Enterprise Linux システムは、 Red Hat サブスクリプション管理に登録する必要があります。登録されていない場合、システムは、 Cloud Manager のインストール中に必要なサードパーティソフトウェアをアップデートするためのリポジトリにアクセスできません。
* Cloud Manager インストーラは、インストールプロセス中に複数の URL にアクセスします。アウトバウンドインターネットアクセスがこれらのエンドポイントに許可されていることを確認する必要があります。を参照してください link:reference_networking_cloud_manager.html["Cloud Manager のネットワーク要件"]。


.このタスクについて
* Cloud Manager のインストールにはルート権限は必要ありません。
* Cloud Manager は AWS コマンドラインツール（ AWSCLI ）をインストールして、ネットアップのサポートからのリカバリ手順を有効にします。
+
AWSCLI のインストールに失敗したというメッセージが表示された場合は、このメッセージを無視しても問題ありません。Cloud Manager は、ツールを使用せずに正常に運用できます。

* ネットアップサポートサイトで入手できるインストーラは、それよりも古いバージョンの場合があります。インストール後に新しいバージョンが利用可能になると、 Cloud Manager は自動的に更新されます。


.手順
. ネットワーク要件を確認します。
+
** link:reference_networking_cloud_manager.html["Cloud Manager のネットワーク要件"]
** link:reference_networking_aws.html["Cloud Volumes ONTAP for AWS のネットワーク要件"]
** link:reference_networking_azure.html["Cloud Volumes ONTAP for Azure のネットワーク要件"]


. レビュー link:reference_cloud_mgr_reqs.html["Cloud Manager ホストの要件"]。
. からソフトウェアをダウンロードします http://mysupport.netapp.com/NOW/cgi-bin/software["ネットアップサポートサイト"^]をクリックし、 Linux ホストにコピーします。
+
AWS の EC2 インスタンスに接続してファイルをコピーする方法については、を参照してください http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html["AWS ドキュメント：「 Connecting to Your Linux Instance Using SSH"^]。

. スクリプトを実行する権限を割り当てます。
+
* 例 *

+
 chmod +x OnCommandCloudManager-V3.6.3.sh
. インストールスクリプトを実行します。
+
 ./OnCommandCloudManager-V3.6.3.sh [silent] [proxy=ipaddress] [proxyport=port] [proxyuser=user_name] [proxypwd=password]
+
_silent_ 情報の入力を求めずにインストールを実行します。

+
proxy _ は、 Cloud Manager ホストがプロキシサーバの背後にある場合に指定する必要があります。

+
proxyport_ は、プロキシサーバのポートです。

+
_proxyUser_ は、ベーシック認証が必要な場合に、プロキシサーバのユーザ名です。

+
_proxypwd_は 、指定したユーザー名のパスワードです。

. silent パラメータを指定しなかった場合は、「 * Y * 」と入力してスクリプトを続行し、プロンプトが表示されたら HTTP ポートと HTTPS ポートを入力します。
+
HTTP ポートと HTTPS ポートを変更する場合は、ユーザがリモートホストから Cloud Manager Web コンソールにアクセスできることを確認する必要があります。

+
** セキュリティグループを変更して、ポート経由の着信接続を許可します。
** Cloud Manager Web コンソールへの URL を入力するときにポートを指定します。
+
Cloud Manager がインストールされました。プロキシサーバを指定した場合、インストールの最後に Cloud Manager Service （ OCCM ）が 2 回再起動します。



. Web ブラウザを開き、次の URL を入力します。
+
https://_ipaddress_:__port__[]

+
ipaddress _ には、 Cloud Manager ホストの設定に応じて、ローカルホスト、プライベート IP アドレス、またはパブリック IP アドレスを指定できます。たとえば、 Cloud Manager がパブリック IP アドレスのないパブリッククラウドにある場合は、 Cloud Manager ホストに接続されているホストからプライベート IP アドレスを入力する必要があります。

+
デフォルトの HTTP （ 80 ）ポートまたは HTTPS （ 443 ）ポートを変更した場合は、 _port_is 必須です。たとえば、 HTTPS ポートが 8443 に変更された場合はと入力します https://_ipaddress_:8443[]

. NetApp Cloud Central アカウントにサインアップするか、すでにアカウントをお持ちの場合はログインします。
. サインアップまたはログインすると、 Cloud Manager によって、このシステムの管理者としてユーザアカウントが自動的に追加されます。
. ログインしたら、この Cloud Manager システムの名前を入力します。


Cloud Manager で Cloud Volumes ONTAP を導入できるように、 AWS アカウントと Azure アカウントの権限を設定します。

* AWS に Cloud Volumes ONTAP を導入する場合は、 link:task_adding_cloud_accounts.html["AWS アカウントをセットアップして、に追加します Cloud Manager の略"]。
* Cloud Volumes ONTAP を Azure に導入する場合は、 link:task_adding_cloud_accounts.html#setting-up-and-adding-azure-accounts-to-cloud-manager["Azure アカウントをセットアップして、に追加します Cloud Manager の略"]。

